SHOW TIMEZONE;

SELECT now();

CREATE Table timeZ (ts TIMESTAMP WITHOUT TIME ZONE, tsz TIMESTAMP WITH TIME ZONE);

INSERT INTO timez VALUES ('2024-01-12 10:45:00', '2024-01-12 10:45:00');

SELECT * FROM timez;

SELECT CURRENT_DATE;

SELECT now()::DATE;
SELECT now()::TIME;

SELECT to_char(now(), 'dd/mm/yyyy');
SELECT to_char(now(), 'Month');

SELECT CURRENT_DATE - INTERVAL '1 year 2 month';

SELECT age(CURRENT_DATE, '1994-05-21');

SELECT *, age(CURRENT_DATE, dob) FROM students;

SELECT extract(YEAR FROM '2024-01-25':: DATE);
SELECT extract(DAY FROM '2024-01-25':: DATE);

SELECT 1::BOOLEAN;
SELECT 0::BOOLEAN;